### ISSUE TITLE
Getting wrong TYPE value

### ISSUE THREAD

**Issue by maulik-dodia** [handstandsam/androidx-biometric-ux#12]
For type I'm getting different value in different devices.

1. For Motorola X4, Android 9, enrolled finger print & 4 digit pin then getting **Fingerprint**
2. For Realme X2, Android 10, no biometric enrolled, only 6 digit password enrolled then getting **Multiple**
3. For Realme X2, Android 10, only finger print enrolled & 6 digit password enrolled then getting **Multiple**

**Comment by handstandsam** [comment]
Archiving this repo, check out the related issue on the [Google Issue Tracker](https://issuetracker.google.com/issues/111315641).
