### ISSUE TITLE
Fix `Unknown` Logic.  It currently won't ever be returned.

### ISSUE THREAD

**Issue by handstandsam** [handstandsam/androidx-biometric-ux#7]
@fcopardo mentioned that `NONE_ENROLLED` may be returned on devices without biometrics.  Maybe we should remove the `Unknown` sealed class, and just try to keep the library up to date?

![Screen Shot 2020-01-06 at 10 13 40 AM](https://user-images.githubusercontent.com/264948/71826985-3fe8a080-306d-11ea-981c-d059dd76bc15.png)

With currently logic, this isn't a problem, but `Unknown` was supposed to represent this case, however in the code, it isn't happening that way right now.

cc: @evant

**Comment by evant** [comment]
> Unknown was supposed to represent this case

I was under the impression unknown was supposed to represent a new version of biometrics the lib didn't support? Ex: `canAuthenticate()` returning true but the package manager checks all returning false. I'm I misunderstanding things?

**Comment by handstandsam** [comment]
@evant - You are totally right.  Agreed.  Wanted to address what @fcopardo said, but if it's truly an issue, should be reported as a bug to Google's AndroidX lib.

Going to re-purpose this issue now though, because the logic is currently wrong.

https://github.com/handstandsam/biometricks/blob/master/biometricks/src/main/java/com/handstandsam/biometricks/internal/BiometricksHelper.kt#L52-L62

Should say:
`availableFeatures.isEmpty() -> Biometricks.Unknown`

instead of current:

`availableFeatures.isEmpty() -> Biometricks.None`

----

Need to add in some unit tests for these sorts of scenarios!

**Comment by handstandsam** [comment]
Fixed in #8
